"""Utilities for parsing UPS logs and preparing dashboard data."""

from datetime import date, datetime
from typing import Any, NamedTuple, Optional

DATA_FILE = "data.txt"
DATE_FORMAT = "%Y-%m-%d"
LOG_DATE_FORMAT = "%Y,%m,%d"
MAX_CHART_POINTS = 500

# Log rows are generated by upslog with semicolon-separated NUT variables.
# The current format is:
# date; time; battery.charge; input.voltage; battery.voltage; status; load; runtime
#
# Field mapping:
#   parts[0] -> log date emitted by %TIME @Y,@m,@d
#   parts[1] -> log time emitted by %TIME @H,@M,@S
#   parts[2] -> battery charge percentage
#   parts[3] -> utility input voltage
#   parts[4] -> battery voltage
#   parts[5] -> UPS status, such as OL or OB
#   parts[6] -> UPS load percentage
#   parts[7] -> optional battery runtime in seconds
#
# The parser intentionally accepts both old and new log layouts. Historical
# data has seven fields and new rows add battery.runtime as the eighth field.
#
# Values are normalized here before reaching Flask. The template should not
# know about NUT field order, missing historical runtime data, or date parsing.


class UpsReading(NamedTuple):
    """Single parsed UPS log row."""

    label: str
    charge: int
    input_voltage: float
    battery_voltage: float
    status: str
    load: int
    runtime_seconds: Optional[int]


def parse_date(value: str) -> date:
    """Parse an ISO date query value."""

    return datetime.strptime(value, DATE_FORMAT).date()


def parse_date_range(
    start_value: Optional[str],
    end_value: Optional[str],
) -> tuple[date, date, str, str]:
    """Parse selected dates or fall back to today's date."""

    # Invalid or missing filters should not break the dashboard.
    today_str = date.today().isoformat()
    start_arg = start_value or today_str
    end_arg = end_value or today_str

    try:
        return parse_date(start_arg), parse_date(end_arg), start_arg, end_arg
    except ValueError:
        return date.today(), date.today(), today_str, today_str


def format_runtime(seconds: Optional[int]) -> str:
    """Format a NUT battery.runtime value into a dashboard label."""

    # Old log rows do not have battery.runtime, so keep them displayable.
    if seconds is None:
        return "N/D"

    # NUT reports runtime in seconds; the UI is easier to scan in hours/minutes.
    minutes = max(0, round(seconds / 60))
    hours, remaining_minutes = divmod(minutes, 60)

    if hours:
        return f"{hours}h {remaining_minutes:02d}min"

    return f"{remaining_minutes}min"


def build_label(file_date: date, time_value: str, multi_day: bool) -> str:
    """Build the chart label for single-day or multi-day ranges."""

    # upslog stores time as H,M,S, while Chart.js labels read better as H:M:S.
    time_display = time_value.replace(",", ":")
    if not multi_day:
        return time_display

    return f"{file_date.strftime('%d/%m')} {time_display}"


def parse_runtime(parts: list[str]) -> Optional[int]:
    """Parse optional battery.runtime seconds from a split log row."""

    # Keep backward compatibility with existing seven-column data.txt rows.
    if len(parts) <= 7 or not parts[7]:
        return None

    return int(float(parts[7]))


def parse_log_line(
    line: str,
    start_date: date,
    end_date: date,
) -> Optional[UpsReading]:
    """Parse one upslog row if it belongs to the selected date range."""

    # Bad log lines are ignored so one corrupt sample does not hide all charts.
    parts = [part.strip() for part in line.split(";")]

    if len(parts) < 7:
        return None

    try:
        file_date = datetime.strptime(parts[0], LOG_DATE_FORMAT).date()
        if not start_date <= file_date <= end_date:
            return None

        # Column positions mirror the upslog command documented in README.md.
        return UpsReading(
            label=build_label(file_date, parts[1], start_date != end_date),
            charge=int(float(parts[2])),
            input_voltage=float(parts[3]),
            battery_voltage=float(parts[4]),
            status=parts[5],
            load=int(float(parts[6])),
            runtime_seconds=parse_runtime(parts),
        )
    except (IndexError, ValueError):
        return None


def load_readings(start_date: date, end_date: date) -> list[UpsReading]:
    """Load all parseable UPS readings from the local data file."""

    readings = []

    try:
        # Read the file as text logs; parsing remains tolerant per line.
        with open(DATA_FILE, "r", encoding="utf-8") as data_file:
            for line in data_file:
                reading = parse_log_line(line, start_date, end_date)
                if reading:
                    readings.append(reading)
    except FileNotFoundError:
        print("Data file not found.")

    return readings


def percentile(values: list[float], percent: float) -> float:
    """Return a simple nearest-rank percentile value."""

    # This is sufficient for dashboard summaries and avoids a numpy dependency.
    sorted_values = sorted(values)
    index = max(0, int(len(sorted_values) * percent) - 1)
    return sorted_values[index]


def build_stats(readings: list[UpsReading]) -> dict[str, Any]:
    """Build summary values displayed in the dashboard cards."""

    # Empty date ranges render the no-data state in the template.
    if not readings:
        return {}

    # Input voltage and UPS load are the historical series summarized in cards.
    # Battery charge, battery voltage, runtime, and status are point-in-time
    # values, so the dashboard shows the newest reading in the selected range.
    input_voltages = [reading.input_voltage for reading in readings]
    loads = [reading.load for reading in readings]
    last_reading = readings[-1]

    # The keys below match the Jinja template names. Keeping that mapping here
    # makes template changes straightforward and avoids calculations in HTML.
    return {
        "voltage_min": round(min(input_voltages), 1),
        "voltage_max": round(max(input_voltages), 1),
        "voltage_avg": round(sum(input_voltages) / len(input_voltages), 1),
        "voltage_p99": round(percentile(input_voltages, 0.99), 1),
        "voltage_last": last_reading.input_voltage,
        "battery_voltage_last": last_reading.battery_voltage,
        "battery_charge_last": last_reading.charge,
        "runtime_last": format_runtime(last_reading.runtime_seconds),
        "load_last": last_reading.load,
        "load_avg": round(sum(loads) / len(loads), 1),
        "status_last": last_reading.status,
        "count": len(readings),
    }


def downsample(values: list[Any]) -> list[Any]:
    """Limit large chart datasets to keep browser rendering responsive."""

    # Keep the time-series shape while avoiding thousands of canvas points.
    if len(values) <= MAX_CHART_POINTS:
        return values

    step = len(values) // MAX_CHART_POINTS
    return values[::step]


def build_dashboard_context(
    start_value: Optional[str],
    end_value: Optional[str],
) -> dict[str, Any]:
    """Build the template context for the UPS dashboard."""

    # The Flask route passes raw query args; this layer normalizes them.
    start_date, end_date, start_arg, end_arg = parse_date_range(
        start_value,
        end_value,
    )
    readings = load_readings(start_date, end_date)

    # Jinja receives plain lists/dicts so templates stay presentation-focused.
    return {
        "labels": downsample([reading.label for reading in readings]),
        "voltages": downsample(
            [reading.input_voltage for reading in readings]
        ),
        "battery_voltages": downsample(
            [reading.battery_voltage for reading in readings]
        ),
        "loads": downsample([reading.load for reading in readings]),
        "stats": build_stats(readings),
        "start_date": start_arg,
        "end_date": end_arg,
    }
